### ISSUE TITLE
Hatalı Linklendirme

### ISSUE THREAD

**Issue by KatayR** [taylanbildik/bash_script_dersleri#1]
Selamlar.

ReadMe'deki başlıklara yanlış link verilmiş. "Değişkenler"den sonrası hep aynı sayfaya yönlendiriyor:

<img width="468" alt="image" src="https://github.com/taylanbildik/bash_script_dersleri/assets/106617809/47bc6576-a902-4147-8849-516723bc2708">

**Comment by taylanbildik** [comment]
Haklısınız, doküman içeriği tam değil. Bu sebeple bağlantılarda problem mevcut. Kısa vadede güncelleme planım bulunmuyor olsa da ileride güncellemek istediğim için repoyu bu şekilde tutuyorum. 
Vakit ayırıp bildirimde bulunduğunuz için teşekkür ederim.
